server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/blog_app_db
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

springdoc.swagger-ui.path=/swagger-ui.html

app.jwt.secret=blogappsupersecretkeyblogappsupersecretkey2026
app.jwt.expiration-ms=86400000

app.file.upload-dir=uploads

app.seed.admin-email=admin@blogapp.local
app.seed.admin-password=12345
app.seed.admin-name=System Administrator
